version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      #- http.max_content_length=5mb
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  
  kibana:
    depends_on:
      - es01
    image: docker.elastic.co/kibana/kibana:7.17.4
    container_name: kibana
    environment: 
       ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5601:5601
    networks:
      - elastic
  logstash:
    depends_on: 
      - es01
    image: docker.elastic.co/logstash/logstash:7.17.4
    container_name: logstash
    volumes: 
      - ./logstash-settings/logstash-input-redis-output-elatic.config:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash-settings/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
     
    networks:
      - elastic     
     
  #   ports: 
  #     - 9600:9600
  #   networks:
  #     - elastic
  redis:
    depends_on: 
      - es01
    image: redis:5.0
    container_name: redis
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 6379:6379
    networks:
      - elastic  

volumes:
  data01:
    driver: local
  data02:
    driver: local
networks:
  elastic:
    driver: bridge